version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: graveyard-db
    restart: always
    environment:
      POSTGRES_DB: Graveyard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
    container_name: graveyard-backend
    restart: always
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5151
      ConnectionStrings__DefaultConnection: |
        Host=postgres;
        Port=5432;
        Database=graveyard;
        Username=postgres;
        Password=postgres
    ports:
      - "5151:5151"

  frontend:
    build:
      context: ./frontend
    container_name: graveyard-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
